
services:
  app:
    build: .
    container_name: messageapp
    working_dir: /usr/src/app
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - app:/usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm start

  postgres:
    image: postgres:15
    container_name: messageapp_db
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: messageapp
      POSTGRES_PASSWORD: TheFirstTest
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ここは各自のメールアドレス
      PGADMIN_DEFAULT_PASSWORD: nn123mm
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  app:
  postgres:
  pgadmin:
